using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using TreeNodeSourceGenerator;

namespace TreeNodeSourceGenerator
{
    public partial class NodeAccessorSourceGenerator
    {
        private enum AccessOperation
        {
            Get,
            Set,
            Remove,
            ValidatePath,
            GetAllInPath,
            CollectNodes,
        }
        private string GeneratePropertyAccessorPartialClass(INamedTypeSymbol nodeType, List<AccessibleMemberInfo> accessibleMembers)
        {
            var className = nodeType.Name;
            var namespaceName = nodeType.ContainingNamespace.ToDisplayString();
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using TreeNode.Runtime;");
            sb.AppendLine("using TreeNode.Utility;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using static TreeNode.Runtime.TypeCacheSystem;");
            sb.AppendLine("using static TreeNode.Runtime.MultiLevelNavigationEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            string typeKeyword = nodeType.TypeKind == TypeKind.Struct ? "struct" : "class";
            sb.AppendLine($"    public partial {typeKeyword} {className} : IPropertyAccessor");
            sb.AppendLine("    {");

            GenerateAccessMethod(sb, nodeType, accessibleMembers, AccessOperation.Get);
            GenerateAccessMethod(sb, nodeType, accessibleMembers, AccessOperation.Set);
            GenerateAccessMethod(sb, nodeType, accessibleMembers, AccessOperation.Remove);
            GenerateAccessMethod(sb, nodeType, accessibleMembers, AccessOperation.ValidatePath);
            GenerateAccessMethod(sb, nodeType, accessibleMembers, AccessOperation.GetAllInPath);
            GenerateAccessMethod(sb, nodeType, accessibleMembers, AccessOperation.CollectNodes);

            // 生成预编译的 TypeInfo 属性
            GenerateTypeInfoProperty(sb, nodeType);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void GenerateAccessMethod(StringBuilder sb, INamedTypeSymbol nodeType, List<AccessibleMemberInfo> members, AccessOperation operation)
        {
            var (ReturnType, EmptyHandling, IndexErrorHandling) = GetMethodInfo(operation, nodeType.Name, members);
            string override_keyword = ImplementsIPropertyAccessor(nodeType) ? "override " : "";
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        public {override_keyword}{ReturnType}");
            sb.AppendLine("        {");

            if (operation == AccessOperation.ValidatePath)
            {
                GenerateValidatePathMethod(sb, members);
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            if (operation == AccessOperation.GetAllInPath)
            {
                GenerateGetAllInPathMethod(sb, members);
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            if (operation == AccessOperation.CollectNodes)
            {
                GenerateCollectNodesMethod(sb, members);
                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            if (members.Count == 0)
            {
                sb.AppendLine($"            {EmptyHandling}");
                sb.AppendLine("        }");
                return;
            }

            sb.AppendLine("            ref PAPart first =ref path.Parts[index];");

            sb.AppendLine($"            if (first.IsIndex) {{ {IndexErrorHandling} }}");

            sb.AppendLine("            if (index == path.Parts.Length - 1)");

            sb.AppendLine("            {");
            GenerateSinglePathLogic(sb, members, operation, nodeType.Name);
            sb.AppendLine("            }");
            sb.AppendLine("            index++;");
            GenerateMultiPathLogic(sb, members, operation, nodeType.Name);

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private (string ReturnType, string EmptyHandling, string IndexErrorHandling) GetMethodInfo(AccessOperation operation, string nodeTypeName, List<AccessibleMemberInfo> members)
        {
            var validFields = GetValidFieldsInfo(members, operation);
            var indexErrorMsg = $"throw new NotSupportedException($\"{nodeTypeName} 不支持索引访问。请使用属性访问。可用属性: {validFields}\");";
            
            return operation switch
            {
                AccessOperation.Get => (
                    "T GetValueInternal<T>(ref PAPath path,ref int index)",
                    $"throw new NotSupportedException(\"{nodeTypeName} 中没有可读属性或字段可用于获取值。\");",
                    indexErrorMsg
                ),
                AccessOperation.Set => (
                    "void SetValueInternal<T>(ref PAPath path,ref int index, T value)",
                    $"throw new NotSupportedException(\"{nodeTypeName} 中没有可写属性或字段可用于设置值。\");",
                    indexErrorMsg
                ),
                AccessOperation.Remove => (
                    "void RemoveValueInternal(ref PAPath path,ref int index)",
                    $"throw new NotSupportedException(\"{nodeTypeName} 中没有可删除属性或字段可用于删除值。\");",
                    indexErrorMsg
                ),
                AccessOperation.ValidatePath => (
                    "void ValidatePath(ref PAPath path,ref int index)",
                    "// No validation needed for empty type",
                    "// Index access validation not needed for ValidatePath"
                ),
                AccessOperation.GetAllInPath => (
                    "void GetAllInPath<T>(ref PAPath path,ref int index, List<(int depth, T value)> list)  where T : class",
                    "// No handling needed for empty type",
                    indexErrorMsg
                ),
                AccessOperation.CollectNodes => (
                    "void CollectNodes(List<(PAPath, JsonNode)> list, PAPath parent, int depth = -1)",
                    "// No handling needed for empty type",
                    indexErrorMsg
                ),
                _ => throw new ArgumentException($"Unknown operation: {operation}")
            };
        }

        private void GenerateSinglePathLogic(StringBuilder sb, List<AccessibleMemberInfo> members, AccessOperation operation, string typeName)
        {
            var targetMembers = operation == AccessOperation.Set || operation == AccessOperation.Remove
                ? members.Where(m => m.CanWrite && !m.IsReadOnly).ToList()
                : members;

            if (!targetMembers.Any()) return;

            sb.AppendLine("                switch (first.Name)");
            sb.AppendLine("                {");

            foreach (var member in targetMembers)
            {
                sb.AppendLine($"                    case \"{member.Name}\":");
                if (operation != AccessOperation.Remove)
                {
                    GenerateInstanceCreationIfNeeded(sb, member);
                }
                GenerateSinglePathMemberAccess(sb, member, operation);
            }

            var validFields = GetValidFieldsInfo(members, operation);
            sb.AppendLine("                    default:");
            sb.AppendLine($"                        {GetSinglePathDefaultCase(operation, typeName, validFields)}");
            sb.AppendLine("                }");
        }

        private void GenerateMultiPathLogic(StringBuilder sb, List<AccessibleMemberInfo> members, AccessOperation operation, string typeName)
        {
            var multiPathMembers = operation == AccessOperation.Set || operation == AccessOperation.Remove
                ? members.Where(m => (m.HasNestedAccess || m.IsCollection) && m.CanWrite && !m.IsReadOnly).ToList()
                : members.Where(m => m.HasNestedAccess || m.IsCollection).ToList();

            if (!multiPathMembers.Any())
            {
                if (members.Any())
                {
                    sb.AppendLine($"            {GetMultiPathEmptyHandling(operation, typeName, members)}");
                }
                return;
            }

            sb.AppendLine("            switch (first.Name)");
            sb.AppendLine("            {");

            foreach (var member in multiPathMembers)
            {
                sb.AppendLine($"                case \"{member.Name}\":");
                GenerateMultiPathMemberAccess(sb, member, operation);
            }

            var validFields = GetValidMultiPathFieldsInfo(members, operation);
            sb.AppendLine("                default:");
            sb.AppendLine($"                    {GetMultiPathDefaultCase(operation, typeName, validFields)}");
            sb.AppendLine("            }");
        }

        private void GenerateInstanceCreationIfNeeded(StringBuilder sb, AccessibleMemberInfo member)
        {
            if (NeedCreateInstance(member))
            {
                sb.AppendLine($"                    {member.Name}??=new();");
            }
        }

        private void GenerateSinglePathMemberAccess(StringBuilder sb, AccessibleMemberInfo member, AccessOperation operation)
        {
            switch (operation)
            {
                case AccessOperation.Get:
                    sb.AppendLine($"                        return ({member.Name} is T _{member.Name}) ? _{member.Name} : default(T);");
                    break;
                case AccessOperation.Set:
                    sb.AppendLine($"                        if (value is {member.Type.ToDisplayString()} _{member.Name}) {{ {member.Name} = _{member.Name}; return; }}");
                    sb.AppendLine($"                        throw new InvalidCastException($\"无法将 {{typeof(T).Name}} 转换为属性 '{member.Name}' 的类型 {member.Type.ToDisplayString()}。期望类型: {member.Type.ToDisplayString()}，实际类型: {{typeof(T).FullName}}\");");
                    break;
                case AccessOperation.Remove:
                    if (member.IsValueType)
                    {
                        sb.AppendLine($"                        {member.Name} = default({member.Type.ToDisplayString()}); return;");
                    }
                    else
                    {
                        sb.AppendLine($"                        {member.Name} = null; return;");
                    }
                    break;
            }
        }

        private void GenerateMultiPathMemberAccess(StringBuilder sb, AccessibleMemberInfo member, AccessOperation operation)
        {
            if (member.IsCollection)
            {
                GenerateInstanceCreationIfNeeded(sb, member);
                GenerateCollectionAccess(sb, member, operation);
            }
            else if (member.HasNestedAccess)
            {
                GenerateNestedAccess(sb, member, operation);
            }
        }

        private void GenerateCollectionAccess(StringBuilder sb, AccessibleMemberInfo member, AccessOperation operation)
        {
            var accessMethod = operation switch
            {
                AccessOperation.Get => $"return {member.Name}.GetValueInternal<T>(ref path,ref index);",
                AccessOperation.Set => $"{member.Name}.SetValueInternal(ref path,ref index, value);return;",
                AccessOperation.Remove => $"{member.Name}.RemoveValueInternal(ref path,ref index);return;",
                _ => throw new ArgumentException($"Unknown operation: {operation}")
            };

            sb.AppendLine($"                    {accessMethod}");
        }

        private void GenerateNestedAccess(StringBuilder sb, AccessibleMemberInfo member, AccessOperation operation)
        {
            bool needCreateInstance = NeedCreateInstance(member);
            if (needCreateInstance && operation != AccessOperation.Remove)
            {
                sb.AppendLine($"                        {member.Name}??=new();");
            }

            bool structProperty = member.IsValueType && member.IsProperty && (operation is AccessOperation.Set or AccessOperation.Remove);

            if (structProperty)
            {
                // 对于 struct 属性，需要通过临时变量进行操作
                sb.AppendLine($"                    var temp_{member.Name} = {member.Name};");

                var accessMethod = GetNestedAccessMethodForStruct(member, operation, $"temp_{member.Name}");
                sb.AppendLine($"                    {accessMethod}");
                sb.AppendLine($"                    {member.Name} = temp_{member.Name};");
                sb.AppendLine($"                    return;");
            }
            else
            {
                var accessMethod = GetNestedAccessMethod(member, operation);

                string nullCheck = (member.IsValueType || needCreateInstance)
                    ? accessMethod
                    : $"if ({member.Name} != null) {{ {accessMethod} }}";

                sb.AppendLine($"                    {nullCheck}");

                if (!member.IsValueType && !needCreateInstance)
                {
                    sb.AppendLine($"                    throw new NullReferenceException($\"属性 '{member.Name}' 为空，无法继续路径导航。属性类型: {member.Type.ToDisplayString()}。建议在访问嵌套路径之前初始化此属性。\");");
                }
            }
        }

        private string GetNestedAccessMethod(AccessibleMemberInfo member, AccessOperation operation)
        {
            var multiLevelEngineAccess = operation switch
            {
                AccessOperation.Get => $"return ProcessMultiLevel_GetValue<T>({member.Name}, ref path,ref index);",
                AccessOperation.Set => $"ProcessMultiLevel_SetValue({member.Name},ref path,ref index, value);return;",
                AccessOperation.Remove => $"ProcessMultiLevel_RemoveValue({member.Name},ref path,ref index);return;",
                _ => throw new ArgumentException($"Unknown operation: {operation}")
            };
            return multiLevelEngineAccess;
        }

        private string GetNestedAccessMethodForStruct(AccessibleMemberInfo member, AccessOperation operation, string tempVarName)
        {
            var multiLevelEngineAccess = operation switch
            {
                AccessOperation.Get => $"return ProcessMultiLevel_GetValue<T>({tempVarName}, ref path,ref index);",
                AccessOperation.Set => $"ProcessMultiLevel_SetValue({tempVarName},ref path,ref index, value);",
                AccessOperation.Remove => $"ProcessMultiLevel_RemoveValue({tempVarName},ref path,ref index);",
                _ => throw new ArgumentException($"Unknown operation: {operation}")
            };

            return multiLevelEngineAccess;
        }

        private string GetValidFieldsInfo(List<AccessibleMemberInfo> members, AccessOperation operation)
        {
            var targetMembers = operation switch
            {
                AccessOperation.Set => members.Where(m => m.CanWrite && !m.IsReadOnly).ToList(),
                AccessOperation.Remove => members.Where(m => m.CanWrite && !m.IsReadOnly).ToList(),
                _ => members
            };

            if (!targetMembers.Any())
            {
                return "[无]";
            }

            return string.Join(", ", targetMembers.Select(m => $"{m.Name}({m.Type.Name})"));
        }

        private string GetValidMultiPathFieldsInfo(List<AccessibleMemberInfo> members, AccessOperation operation)
        {
            var multiPathMembers = operation == AccessOperation.Set || operation == AccessOperation.Remove
                ? members.Where(m => (m.HasNestedAccess || m.IsCollection) && m.CanWrite && !m.IsReadOnly).ToList()
                : members.Where(m => m.HasNestedAccess || m.IsCollection).ToList();

            if (!multiPathMembers.Any())
            {
                return "[无]";
            }

            return string.Join(", ", multiPathMembers.Select(m => $"{m.Name}({m.Type.Name})"));
        }

        private string GetSinglePathDefaultCase(AccessOperation operation, string typeName, string validFields)
        {
            return operation switch
            {
                AccessOperation.Get => $"throw new NotSupportedException($\"属性 '{{first.Name}}' 在 {typeName} 中未找到。可用属性: {validFields}\");",
                AccessOperation.Set => $"throw new NotSupportedException($\"属性 '{{first.Name}}' 在 {typeName} 中未找到或不可写。可写属性: {validFields}\");",
                AccessOperation.Remove => $"throw new NotSupportedException($\"属性 '{{first.Name}}' 在 {typeName} 中未找到或不可删除。可删除属性: {validFields}\");",
                _ => throw new ArgumentException($"Unknown operation: {operation}")
            };
        }

        private string GetMultiPathDefaultCase(AccessOperation operation, string typeName, string validFields)
        {
            return operation switch
            {
                AccessOperation.Get => $"throw new NotSupportedException($\"以 '{{first.Name}}' 开头的路径在 {typeName} 中不受支持。可用的多路径属性: {validFields}\");",
                AccessOperation.Set => $"throw new NotSupportedException($\"以 '{{first.Name}}' 开头的路径在 {typeName} 中不受支持或不可写。可写的多路径属性: {validFields}\");",
                AccessOperation.Remove => $"throw new NotSupportedException($\"以 '{{first.Name}}' 开头的路径在 {typeName} 中不受支持或不可删除。可删除的多路径属性: {validFields}\");",
                _ => throw new ArgumentException($"Unknown operation: {operation}")
            };
        }

        private string GetMultiPathEmptyHandling(AccessOperation operation, string typeName, List<AccessibleMemberInfo> members)
        {
            var singlePathFields = GetValidFieldsInfo(members, operation);
            return operation switch
            {
                AccessOperation.Get => $"throw new NotSupportedException(\"{typeName} 中没有可用于获取值的多路径属性或字段。可用的单路径属性: {singlePathFields}\");",
                AccessOperation.Set => $"throw new NotSupportedException(\"{typeName} 中没有可用于设置值的多路径属性或字段。可用的单路径可写属性: {singlePathFields}\");",
                AccessOperation.Remove => $"throw new NotSupportedException(\"{typeName} 中没有可用于删除值的多路径属性或字段。可用的单路径可删除属性: {singlePathFields}\");",
                _ => throw new ArgumentException($"Unknown operation: {operation}")
            };
        }

        private void GenerateValidatePathMethod(StringBuilder sb, List<AccessibleMemberInfo> members)
        {
            sb.AppendLine("            ref PAPart part = ref path.Parts[index];");
            sb.AppendLine("            if (part.IsIndex)");
            sb.AppendLine("            {");
            sb.AppendLine("                index--;");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();

            if (members.Count == 0)
            {
                sb.AppendLine("            index--;");
                sb.AppendLine("            return;");
                return;
            }

            sb.AppendLine("            switch (part.Name)");
            sb.AppendLine("            {");

            // 先处理终端字段（基础类型），无论单路径还是多路径都是有效的终点
            var terminalMembers = members.Where(m => !(m.HasNestedAccess || m.IsCollection)).ToList();
            if (terminalMembers.Any())
            {
                foreach (var member in terminalMembers)
                {
                    sb.AppendLine($"                case \"{member.Name}\":");
                }
                sb.AppendLine("                    return;");  // 终端字段，路径有效
            }

            // 处理需要null检查的嵌套类型字段
            var nestedMembers = members.Where(m => m.HasNestedAccess || m.IsCollection).ToList();
            foreach (var member in nestedMembers)
            {
                sb.AppendLine($"                case \"{member.Name}\":");

                // 先进行null检查（对于不会自动创建且是引用类型的成员）
                bool needCreateInstance = NeedCreateInstance(member);
                if (!member.IsValueType && !needCreateInstance)
                {
                    sb.AppendLine($"                    if ({member.Name} == null){{return;}}");
                }

                // 然后进行单路径判断
                sb.AppendLine("                    if (index == path.Parts.Length - 1){return;}");

                // 最后是多路径递归验证
                sb.AppendLine("                    index++;");

                if (member.IsCollection)
                {
                    sb.AppendLine($"                    ProcessMultiLevel_ValidatePath({member.Name}, ref path, ref index);");
                    sb.AppendLine("                    return;");
                }
                else // member.HasNestedAccess
                {
                    sb.AppendLine($"                    ProcessMultiLevel_ValidatePath({member.Name}, ref path, ref index);");
                    sb.AppendLine("                    return;");
                }
            }

            sb.AppendLine("                default:");
            sb.AppendLine("                    index--;");  // 属性不存在，路径无效
            sb.AppendLine("                    return;");
            sb.AppendLine("            }");
        }

        private void GenerateGetAllInPathMethod(StringBuilder sb, List<AccessibleMemberInfo> members)
        {
            sb.AppendLine("            ref PAPart part = ref path.Parts[index];");
            sb.AppendLine("            if (part.IsIndex)");
            sb.AppendLine("            {");
            sb.AppendLine("                index--;");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();

            // 过滤出引用类型成员，但排除string类型
            var referenceTypeMembers = members.Where(m => !m.IsValueType &&
                m.Type.SpecialType != SpecialType.System_String).ToList();

            if (referenceTypeMembers.Count == 0)
            {
                sb.AppendLine("            index--;");
                sb.AppendLine("            return;");
                return;
            }

            sb.AppendLine("            switch (part.Name)");
            sb.AppendLine("            {");

            foreach (var member in referenceTypeMembers)
            {
                sb.AppendLine($"                case \"{member.Name}\":");
                bool needCreateInstance = NeedCreateInstance(member);
                if (!needCreateInstance)
                {
                    sb.AppendLine($"                    if ({member.Name} == null){{index--;return;}}");
                }
                else
                {
                    sb.AppendLine($"                    {member.Name}??=new();");
                }
                // 检查当前成员是否为目标类型T，如果是则添加到列表中并作为终点返回
                sb.AppendLine($"                    if ({member.Name} is T value_{member.Name})");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        list.Add((index, value_{member.Name}));");
                sb.AppendLine("                    }");

                // 如果不是目标类型T，且这是路径的终点，则返回
                sb.AppendLine("                    if (index == path.Parts.Length - 1){return;}");

                // 如果不是终点且成员支持嵌套访问或是集合，则继续递归
                if (member.HasNestedAccess || member.IsCollection)
                {
                    sb.AppendLine("                    index++;");
                    sb.AppendLine($"                    ProcessMultiLevel_GetAllInPath({member.Name}, ref path, ref index, list);");
                }

                sb.AppendLine("                    return;");
            }

            sb.AppendLine("                default:");
            sb.AppendLine("                    index--;");  // 属性不存在，路径无效
            sb.AppendLine("                    return;");  // 属性不存在，直接返回
            sb.AppendLine("            }");
        }

        /// <summary>
        /// 生成 CollectNodes 方法
        /// </summary>
        private void GenerateCollectNodesMethod(StringBuilder sb, List<AccessibleMemberInfo> members)
        {
            sb.AppendLine("            if (depth == 0) { return; }");
            sb.AppendLine();

            // 过滤出可能包含嵌套结构的成员（排除基础类型、Vec2类型和带有NoJsonNodeContainer标记的类型）
            var nestableMembers = members.Where(m => 
                m.IsJsonNodeType || 
                m.HasNestedAccess || 
                m.IsCollection || 
                (!m.HasNoJsonNodeContainer&& m.Type.SpecialType != SpecialType.System_String&&!m.IsValueType)
            ).ToList();

            if (nestableMembers.Count == 0)
            {
                return;
            }

            foreach (var member in nestableMembers)
            {
                // 检查成员是否为null（仅对引用类型且不会自动创建实例的成员）
                bool needCreateInstance = NeedCreateInstance(member);
                if (!member.IsValueType && !needCreateInstance)
                {
                    sb.AppendLine($"            if ({member.Name} != null)");
                    sb.AppendLine("            {");
                    GenerateCollectNodesMemberLogic(sb, member, "    ");
                    sb.AppendLine("            }");
                }
                else
                {
                    GenerateCollectNodesMemberLogic(sb, member, "");
                }
                sb.AppendLine();
            }
        }

        private void GenerateCollectNodesMemberLogic(StringBuilder sb, AccessibleMemberInfo member, string indent)
        {
            string memberPath = $"parent.Append(\"{member.Name}\")";
            
            string depth_ = "depth";
            // 如果成员本身是JsonNode类型，直接添加
            if (member.IsJsonNodeType)
            {
                depth_ = "depth > 0 ? depth - 1 : depth"; // 避免修改原始 depth 参数
                sb.AppendLine($"{indent}            list.Add(({memberPath}, {member.Name}));");
            }
            
            // 处理集合类型
            if (member.IsCollection)
            {
                bool needCreateInstance = NeedCreateInstance(member);
                if (needCreateInstance)
                {
                    sb.AppendLine($"{indent}            {member.Name}??=new();");
                }
                sb.AppendLine($"{indent}            {member.Name}.CollectNodes(list, {memberPath}, depth);");
            }
            // 处理具有嵌套访问的成员
            else if (member.HasNestedAccess)
            {
                bool needCreateInstance = NeedCreateInstance(member);
                if (needCreateInstance)
                {
                    sb.AppendLine($"{indent}            {member.Name}??=new();");
                }

                sb.AppendLine($"{indent}            ProcessMultiLevel_CollectNodes({member.Name}, list, {memberPath}, {depth_});");
            }
            // 处理其他可能包含嵌套结构的引用类型成员
            else if (!member.IsValueType && member.Type.SpecialType != SpecialType.System_String)
            {
                sb.AppendLine($"{indent}            ProcessMultiLevel_CollectNodes({member.Name}, list, {memberPath}, depth);");
            }
        }

        /// <summary>
        /// 生成预编译的 TypeInfo 属性，避免反射消耗
        /// </summary>
        private void GenerateTypeInfoProperty(StringBuilder sb, INamedTypeSymbol nodeType)
        {
            var fullTypeName = nodeType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string override_keyword = ImplementsIPropertyAccessor(nodeType) ? "override " : "";
            GeneratePrecompiledTypeReflectionInfo(sb, nodeType, fullTypeName);
            sb.AppendLine($"        [Newtonsoft.Json.JsonIgnore]");
            sb.AppendLine($"        public {override_keyword}TypeReflectionInfo TypeInfo => _typeInfo;");
        }
    }
}